**Valid Sudoku**

In [60]:
import numpy as np

In [61]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

**General Questions**

In [62]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [63]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [64]:
#Find the average age of students.
print(data[:,0].mean())


18.4


In [65]:
#Extract Math marks of all students.
marks=data[:,1]
marks

array([85, 92, 76, 65, 90])

In [66]:
#Find the highest Science mark.
highest=data[:,2].max()
print(highest)


95


In [67]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]


array([[19, 92, 88]])

In [68]:
#Increase Math marks of all students by 5.
data[:,1]+5


array([90, 97, 81, 70, 95])

In [69]:
#Find how many students are younger than 19.
data[data[:,0]<19]

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [70]:
#Calculate the average marks in each subject (column-wise mean).
data[:,1:3].mean(axis=0)

array([81.6, 83.2])

In [71]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [72]:
#Replace all Science marks < 75 with 0.
data[data[:,2]<75,2]=0
data


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])