# NumPy Arrays

| Feature | Python List | NumPy Array |
| :--- | :--- | :--- |
| Data type | Mixed allowed | Same data type only |
| Performance | Slower | Much faster (C-level) |
| Memory efficiency | Low | High |
| Vector operations | Manual loops | Easy + fast |

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

<h1>Array Generation function</h1>

In [5]:
# using range function

array_rang=np.arange(1,11)

In [6]:
array_rang

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
array_zero=np.zeros(6)
array_zero

array([0., 0., 0., 0., 0., 0.])

In [8]:
array_zero_mat=np.zeros((4,6))
array_zero_mat

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
arr_one=np.ones(6)
arr_one

array([1., 1., 1., 1., 1., 1.])

In [10]:
arr_one_mat=np.ones((4,6))
arr_one_mat

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
arr_lin=np.linspace(0,1,100)
arr_lin

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

<h1>Random generation function</h1>

In [12]:
np.random.rand(10)  #numbers will lie in 0 - 1 (Normalisation concept)

array([0.26235375, 0.7558923 , 0.92713962, 0.56128998, 0.68663805,
       0.32499755, 0.71740578, 0.63333238, 0.06772613, 0.96718576])

In [13]:
np.random.randn(10)  #numbers will lie in -3 - 3 (standardisation concept)

array([-0.9941299 , -0.46371742, -0.28797809, -0.04667296, -1.31195173,
       -0.29367855, -1.32950731,  0.94777192, -0.18761551,  1.43008373])

In [14]:
np.random.randint(10)

6

In [15]:
np.random.randint(10,20,10)

array([14, 11, 13, 11, 11, 18, 17, 15, 16, 16], dtype=int32)

In [16]:
#array attributes
arr=[[1,2,3],[4,5,6],[7,8,9]]

In [17]:
arr=np.array(arr)

In [18]:
arr.shape

(3, 3)

In [19]:
arr.size

9

In [20]:
arr.dtype

dtype('int64')

In [21]:
# array methods

arr.min()

np.int64(1)

In [22]:
arr.max()

np.int64(9)

In [23]:
arr.sum()

np.int64(45)

In [24]:
#row wise sum
arr.sum(axis=0)

array([12, 15, 18])

In [25]:
#column wise sum
arr.sum(axis=1)

array([ 6, 15, 24])

In [26]:
arr.mean()

np.float64(5.0)

In [27]:
arr.std()

np.float64(2.581988897471611)

In [28]:
arr.argmax() # max element index value

np.int64(8)

In [29]:
arr.argmin() # min element index value

np.int64(0)

In [30]:
arr=np.arange(1,31)

In [31]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [32]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [33]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [34]:
arr=np.arange(1,31).reshape(6,5)

In [35]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [40]:
arr[2,:]

array([11, 12, 13, 14, 15])

In [41]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [42]:
arr_new=arr[arr%2==0]

In [43]:
arr_new

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])